# Generated by Django 4.1.4 on 2022-12-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_email', models.EmailField(max_length=254)),
                ('post_phone', models.IntegerField()),
                ('post_debt', models.IntegerField()),
                ('post_paid_amt', models.IntegerField()),
                ('post_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Active', max_length=60)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_school', models.CharField(max_length=150)),
                ('school_email_address', models.EmailField(max_length=254)),
                ('location_of_school', models.CharField(max_length=150)),
                ('school_phone', models.IntegerField()),
                ('post_school', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=100)),
                ('student_lastname', models.CharField(max_length=150)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.IntegerField()),
                ('student_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_name', models.CharField(max_length=100)),
                ('Comment_body', models.TextField(max_length=500)),
                ('comment_date_created', models.DateTimeField(auto_now_add=True)),
                ('comment_post', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('school_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
                ('student_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
