# Generated by Django 4.1.4 on 2022-12-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_school_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='school_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='student_comment',
        ),
    ]
