# Generated by Django 4.1.4 on 2022-12-11 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=600)),
                ('phone', models.IntegerField(default=234)),
                ('address', models.CharField(blank=True, max_length=700)),
                ('is_schoolowner', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=400)),
                ('level', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=400)),
                ('is_debtor', models.BooleanField(default=True)),
                ('school_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebtInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_amount', models.CharField(max_length=500)),
                ('debt_status', models.CharField(choices=[('Pending', 'pending'), ('Active', 'active'), ('Paid', 'paid')], default='Active', max_length=200)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
                ('debtor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.debtor')),
            ],
        ),
    ]
