# Generated by Django 4.1.4 on 2022-12-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtor',
            old_name='name',
            new_name='full_name',
        ),
    ]
