# Generated by Django 4.1.4 on 2022-12-08 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolowner',
            old_name='fullname',
            new_name='schoolname',
        ),
        migrations.RemoveField(
            model_name='schoolowner',
            name='item',
        ),
        migrations.AddField(
            model_name='schoolowner',
            name='address',
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name='schoolowner',
            name='phone',
            field=models.IntegerField(default=234),
        ),
        migrations.AddField(
            model_name='schoolowner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
