# Generated by Django 4.1.4 on 2022-12-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_date_created',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_post',
            new_name='post',
        ),
    ]
