# Generated by Django 4.1.4 on 2022-12-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_comment_body_comment_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='debtors_text',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
