# Generated by Django 4.1.4 on 2022-12-12 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_debtors_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='accounts.post')),
            ],
        ),
    ]
