# Generated by Django 4.1.4 on 2022-12-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_school_id_debtor_school_name_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='school_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
    ]
