# Generated by Django 4.1.4 on 2022-12-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtinfo',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school'),
        ),
    ]
