# Generated by Django 4.1.4 on 2022-12-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contend_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contend',
            old_name='user',
            new_name='post',
        ),
    ]
