# Generated by Django 4.1.4 on 2022-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtinfo',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='debtinfo',
            name='debtor_name',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
