# Generated by Django 4.1.4 on 2022-12-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_debtinfo_content_alter_debtinfo_debtor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtinfo',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='debtinfo',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
