# Generated by Django 4.1.4 on 2022-12-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_debtinfo_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtinfo',
            name='debt_amount',
            field=models.IntegerField(max_length=500),
        ),
    ]
