# Generated by Django 4.1.4 on 2022-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_debtinfo_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtinfo',
            name='debt_amount',
            field=models.CharField(max_length=500),
        ),
    ]
