# Generated by Django 4.1.4 on 2022-12-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_debtinfo_debt_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=500)),
                ('debt_amount', models.CharField(max_length=500)),
                ('debt_status', models.CharField(choices=[('Pending', 'pending'), ('Active', 'active'), ('Paid', 'paid')], default='Active', max_length=200)),
                ('content', models.TextField(blank=True)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
        ),
        migrations.DeleteModel(
            name='DebtInfo',
        ),
    ]
