# Generated by Django 4.1.4 on 2022-12-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_post_delete_debtinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
