# Generated by Django 4.1.4 on 2022-12-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_post_options_alter_post_created_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
